<?php

return [
    'company_name' => env('COMPANY_NAME', 'Boztech Bilişim & Güvenlik Sistemleri'),
    'short_name' => 'Boztech Bilişim',
    'phone' => env('COMPANY_PHONE', '0545 565 85 83'),
    'phone_raw' => env('COMPANY_PHONE_RAW', '905455658583'),
    'whatsapp' => env('COMPANY_WHATSAPP', '905455658583'),
    'whatsapp_default_message' => 'Merhaba Boztech Bilişim, güvenlik kamerası satışı ve montajı hakkında bilgi ve ücretsiz keşif talebinde bulunmak istiyorum.',
    'email' => env('COMPANY_EMAIL', 'info@boztechbilisim.com'),
    'working_hours' => 'Haftanın 7 Günü | 08:30 - 20:30 Hızlı Keşif & Montaj',
    'address_text' => 'Dörtyol Merkez / Hatay (Tüm Hatay Bölgesine Gezici Servis)',
    'service_area' => 'Hatay Dörtyol Merkezli (Dörtyol, İskenderun, Payas, Erzin, Antakya, Arsuz, Belen, Kırıkhan ve Tüm İlçeler)',

    'google_ads' => [
        'id' => env('GOOGLE_ADS_ID', null),
        'phone_conversion_label' => env('GOOGLE_ADS_PHONE_LABEL', null),
        'lead_conversion_label' => env('GOOGLE_ADS_LEAD_LABEL', null),
    ],

    'districts' => [
        'dortyol' => [
            'name' => 'Dörtyol (Merkez)',
            'title' => 'Dörtyol Güvenlik Kamerası Satış & Profesyonel Montaj | Boztech Bilişim',
            'slug' => 'dortyol',
            'meta_desc' => 'Hatay Dörtyol merkezli Boztech Bilişim güvenlik kamerası satışı, montajı ve arıza servisi. Ev, iş yeri, narenciye bahçesi ve depo kamera sistemleri.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Dörtyol merkez ve mahallelerinde konut, iş yeri, narenciye arazisi ve depolar için aynı gün ücretsiz yerinde keşif.',
        ],
        'iskenderun' => [
            'name' => 'İskenderun',
            'title' => 'İskenderun Güvenlik Kamera Sistemleri & Kurulumu | Boztech Bilişim',
            'slug' => 'iskenderun',
            'meta_desc' => 'İskenderun kamera montajı ve satışı. Boztech Bilişim ile işyerleri, apartmanlar, depolar ve villalar için IP ve Full HD kamera kurulumu.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Mağaza, depo, site ve villa projelerine özel yüksek çözünürlüklü IP PoE ve gece renkli gösteren kameralar.',
        ],
        'erzin' => [
            'name' => 'Erzin',
            'title' => 'Erzin Güvenlik Kamerası Satış & Montaj | Boztech Bilişim',
            'slug' => 'erzin',
            'meta_desc' => 'Erzin güvenlik kamerası satışı, kurulumu ve teknik servisi. Narenciye bahçeleri, çiftlikler ve evler için garantili montaj.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Narenciye bahçeleri, kaplıca tesisleri, çiftlik ve ev güvenliği için solar ve gece görüşlü kamera paketleri.',
        ],
        'payas' => [
            'name' => 'Payas',
            'title' => 'Payas Güvenlik Kamerası Satış & Teknik Servis | Boztech Bilişim',
            'slug' => 'payas',
            'meta_desc' => 'Payas sanayi ve yerleşim alanları için güvenlik kamera montajı. IP kamera, kayıt cihazı ve mobil izleme kurulumu.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Fabrika, atölye, sanayi kuruluşları ve konut güvenliği için yüksek kaliteli IP kamera sistemleri.',
        ],
        'antakya' => [
            'name' => 'Antakya',
            'title' => 'Antakya Güvenlik Kamerası Satış & Montajı | Boztech Bilişim',
            'slug' => 'antakya',
            'meta_desc' => 'Antakya güvenlik kamerası kurulumu ve satışı. 2, 4, 8 kameralı setler, AHD ve IP kamera sistemleri, aynı gün ücretsiz keşif.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Müstakil evler, prefabrik/konteyner yaşam alanları, iş yerleri ve apartmanlar için net gece görüşlü kamera setleri.',
        ],
        'defne' => [
            'name' => 'Defne',
            'title' => 'Defne Güvenlik Kamerası Montaj & Bakım Servisi',
            'slug' => 'defne',
            'meta_desc' => 'Defne ilçesinde güvenlik kamerası satışı ve profesyonel montaj. Cep telefonundan canlı izleme, 2 yıl garanti ve hızlı servis.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Ev, işletme ve bahçe güvenlikleri için ekonomik ve uzun ömürlü kamera paketleri.',
        ],
        'samandag' => [
            'name' => 'Samandağ',
            'title' => 'Samandağ Güvenlik Kamerası Kurulumu & Satışı',
            'slug' => 'samandag',
            'meta_desc' => 'Samandağ ve sahil bölgesinde nem ve dış ortama dayanıklı güvenlik kamera sistemleri. Aynı gün keşif ve montaj.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Dış ortam, yazlıklar, seralar ve tarım arazileri için korozyona dayanıklı IP ve Solar kamera sistemleri.',
        ],
        'kirikhan' => [
            'name' => 'Kırıkhan',
            'title' => 'Kırıkhan Güvenlik Kamera Sistemleri & Montaj',
            'slug' => 'kirikhan',
            'meta_desc' => 'Kırıkhan güvenlik kamerası satışı, arıza servisi ve anahtar teslim kurulum. En uygun fiyatlı kamera setleri.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Çiftlikler, depolar, dükkanlar ve evler için gece görüşlü güvenilir kamera sistemleri.',
        ],
        'arsuz' => [
            'name' => 'Arsuz',
            'title' => 'Arsuz Güvenlik Kamerası Satış & Montaj',
            'slug' => 'arsuz',
            'meta_desc' => 'Arsuz villaları, siteleri ve işletmeleri için uzaktan izlemeli güvenlik kameraları. Su ve nem korumalı profesyonel sistemler.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Yazlık villalar, butik oteller ve siteler için uzaktan cep telefonu ile anlık bildirimli akıllı kameralar.',
        ],
        'belen' => [
            'name' => 'Belen',
            'title' => 'Belen Güvenlik Kamerası Kurulumu & Fiyatları',
            'slug' => 'belen',
            'meta_desc' => 'Belen güvenlik kamerası montajı ve satışı. Hızlı teknik servis, şeffaf fiyatlandırma ve garantili işçilik.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Yayla evleri, yol kenarı işletmeler ve konutlar için dayanıklı kamera sistemleri.',
        ],
        'reyhanli' => [
            'name' => 'Reyhanlı',
            'title' => 'Reyhanlı Güvenlik Kamera Sistemleri & Montajı',
            'slug' => 'reyhanli',
            'meta_desc' => 'Reyhanlı güvenlik kamerası satışı ve profesyonel kurulum. Uzaktan cep telefonu takibi, 2 yıl garanti.',
            'phone' => '0545 565 85 83',
            'popular_for' => 'Tarım arazileri, ticarethaneler ve evler için 7/24 kayıt yapan gece görüşlü sistemler.',
        ],
    ],

    'installation_fees' => [
        [
            'title' => 'Kamera Başı Standart Montaj Bedeli',
            'price' => '450 ₺ / Adet',
            'desc' => 'Mevcut veya yeni alınan kameranın fiziki montajı, kablo sonlandırma ve açı ayarı.',
        ],
        [
            'title' => 'Kayıt Cihazı (DVR / NVR) & Disk Kurulumu',
            'price' => '650 ₺',
            'desc' => 'Kayıt cihazı yazılım yapılandırması, disk formatlama, kayıt planı oluşturma.',
        ],
        [
            'title' => 'Cep Telefonundan Canlı İzleme Ayarı',
            'price' => 'Ücretsiz (Paketlerimizde Dahil)',
            'desc' => 'Kullanıcı cep telefonlarına (iOS / Android) uygulama kurulumu, modem port / P2P bağlantısı.',
        ],
        [
            'title' => 'Kablo Çekimi & Kanal / Borulama (Metre Başı)',
            'price' => '35 ₺ / Metre',
            'desc' => 'Kanal içi estetik kablolama ve dış cephe korumalı kablo çekimi.',
        ],
        [
            'title' => 'Hatay İçi Yerinde Ücretsiz Keşif',
            'price' => '0 ₺ (Ücretsiz)',
            'desc' => 'Mekanınızda kör nokta tespiti, en doğru kamera sayısı ve kablo güzergahı projelendirmesi.',
        ],
        [
            'title' => 'Arıza Tespiti & Servis Bedeli',
            'price' => '500 ₺',
            'desc' => 'Mevcut eski kamera sisteminizdeki arıza tespiti, adaptör veya bağlantı onarımı.',
        ],
    ],
];
